# Generated by Django 5.2.4 on 2025-08-22 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                    )),
                ('name', models.CharField(
                    max_length=255, unique=True
                    )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True
                    )),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                    )),
                ('full_name', models.CharField(
                    max_length=255
                    )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='profile', 
                    to=settings.AUTH_USER_MODEL
                    )),
            ],
        ),
    ]
