# Generated by Django 5.2.4 on 2025-08-25 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                    )),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    related_name='author_tasks', 
                    to=settings.AUTH_USER_MODEL
                    )),
                ('executor', models.ForeignKey(
                    blank=True, null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='executor_tasks', 
                    to=settings.AUTH_USER_MODEL
                    )),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='task_manager.status'
                    )),
            ],
        ),
    ]
