# Generated by Django 5.2.4 on 2025-09-01 09:15

from django.db import migrations


def populate_description(apps, schema_editor):
    task_model = apps.get_model('task_manager', 'task_model')
    for task in task_model.objects.filter(description__isnull=True):
        task.description = ''
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_label_task_labels'),
    ]

    operations = [
        migrations.RunPython(populate_description),
    ]
