name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./db.sqlite3
      BASE_URL: http://webserver:9000

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync


      - name: Apply database migrations
        run: |
          make migrate

      - name: Run tests
        run: |
          make test
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Lint code
        run: |
          make lint